Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Red_Lake_Hospital_Redesign_Team6.Models;
using Red_Lake_Hospital_Redesign_Team6.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;
using System.Net;

namespace Red_Lake_Hospital_Redesign_Team6.Controllers
{
    public class FeedbackController : Controller
    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static FeedbackController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,

                UseCookies = false
            };
            client = new HttpClient(handler)
            {
                //change this to match your own local port number
                BaseAddress = new Uri("https://localhost:44349/api/")
            };
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }

        private void GetApplicationCookie()
        {
            string token = "";
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback List" Page. Gathers information from the database.
        /// </summary>
        /// <returns>A dynamic "Feedback List" webpage which provides a list of all blogs in the database.</returns>
        /// <example>GET : /Feedback/List</example>
        // GET: Blog/List
        public ActionResult List()
        {
            string url = "feedbackapi/getfeedback";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<FeedbackDto> SelectedFeedback = response.Content.ReadAsAsync<IEnumerable<FeedbackDto>>().Result;
                return View(SelectedFeedback);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback AdminList" Page. Gathers information from the database.
        /// </summary>
        /// <returns>A dynamic "Feedback List" webpage which provides a list of all blogs in the database and admin options.</returns>
        /// <example>GET : /Feedback/AdminList</example>
        // GET: Blog/List
        [Authorize(Roles = "Admin")]
        public ActionResult AdminList()
        {
            GetApplicationCookie();

            string url = "feedbackapi/getfeedback";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<FeedbackDto> SelectedFeedback = response.Content.ReadAsAsync<IEnumerable<FeedbackDto>>().Result;
                return View(SelectedFeedback);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback Show" Page. Gathers information from the database.
        /// </summary>
        /// <param name="id">Id of the Feedback</param>
        /// <returns>A dynamic "Feedback Show" webpage which provides detailes for a selected blog.</returns>
        /// <example>GET : /Feedback/Show/5</example>
        public ActionResult Show(int id)
        {
            ShowFeedbackViewModel ViewModel = new ShowFeedbackViewModel();
            string url = "feedbackapi/findfeedback/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                FeedbackDto SelectedFeedback = response.Content.ReadAsAsync<FeedbackDto>().Result;
                ViewModel.Feedback = SelectedFeedback;
                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback AdminShow" Page. Gathers information from the database.
        /// </summary>
        /// <param name="id">Id of the Feedback</param>
        /// <returns>A dynamic "Feedback Show" webpage which provides detailes for a selected Feedback.</returns>
        /// <example>GET : /Feedback/Show/5</example>
        [Authorize(Roles = "Admin")]
        public ActionResult AdminShow(int id)
        {
            GetApplicationCookie();

            ShowFeedbackViewModel ViewModel = new ShowFeedbackViewModel();
            string url = "feedbackapi/findfeedback/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                FeedbackDto SelectedBlogs = response.Content.ReadAsAsync<FeedbackDto>().Result;
                ViewModel.Feedback = SelectedBlogs;
                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback Create" Page. Adds information from the database.
        /// </summary>
        /// <returns>A dynamic "Feedback Create" webpage which can add a blog entry to the database.</returns>
        /// <example>GET : /Feedback/Create</example>
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            GetApplicationCookie();

            return View();
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback Create" Page. Adds information from the database.
        /// </summary>
        /// <returns>A dynamic "Feedback Create" webpage which can add a blog entry to the database.</returns>
        /// <example>GET : /Feedback/Create</example>
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(FeedbackModel FeedbackInfo)
        {
            GetApplicationCookie();

            Debug.WriteLine(FeedbackInfo.title);
            string url = "feedbackapi/addfeedback";
            Debug.WriteLine(jss.Serialize(FeedbackInfo));
            HttpContent content = new StringContent(jss.Serialize(FeedbackInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback Update" Page. Gathers information from the database.
        /// </summary>
        /// <param name="id">Id of the Feedback</param>
        /// <returns>A dynamic "Feedback Show" webpage which provides a form to input new blog information.</returns>
        /// <example>GET : /Feedback/Update/5</example>
        [Authorize(Roles = "Admin")]
        public ActionResult Update(int id)
        {
            GetApplicationCookie();

            UpdateFeedbackViewModel ViewModel = new UpdateFeedbackViewModel();

            string url = "feedbackapi/findfeedback/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                FeedbackDto SelectedFeedback = response.Content.ReadAsAsync<FeedbackDto>().Result;
                ViewModel.Feedback = SelectedFeedback;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Routes to a dynamically generated "Feedback Update" Page. Gathers information from the database.
        /// </summary>
        /// <param name="id">Id of the Feedback</param>
        /// <returns>A dynamic "Feedback Show" webpage which provides a form to input new blog information.</returns>
        /// <example>GET : /Feedback/Update/5</example>
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Update(int id, FeedbackDto FeedbackInfo)
        {
            GetApplicationCookie();

            string url = "feedbackapi/updatefeedback/" + id;
            HttpContent content = new StringContent(jss.Serialize(FeedbackInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Show", new { id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }



        /// <summary>
        /// Routes to a dynamically generated "Feedback Delete" Page. Gathers information from the database.
        /// </summary>
        /// <param name="id">Id of the Feedback</param>
        /// <returns>A dynamic "Feedback Show" webpage which provides information on a blog that can be deleted.</returns>
        /// <example>GET : /Feedback/Delete/5</example>
        [HttpGet]
        [Authorize(Roles = "Admin")]

Views/Feedback/AdminList.cshtml
@model IEnumerable<Red_Lake_Hospital_Redesign_Team6.Models.FeedbackDto>

@{
    ViewBag.Title = "List";
}

<h2>Feedback List</h2>

<div class="navbar">
    <a class="navlink" href="/Feedback/Create">New Entry</a>
</div>

<table class="table">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            email
        </th>
        <th>
            title
        </th>
        <th>
            text
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.fname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.lname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.text)
    </td>
    <td>
        <a href="/Feedback/AdminShow/@item.feedback_id">Read More</a>
    </td>
</tr>
    }

</table>

Views/Feedback/AdminShow.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.ViewModels.ShowFeedbackViewModel

@{
    ViewBag.Title = "Show";
}

<h2>@Model.Feedback.title</h2>
<div class="navbar">
    <a class="navlink" href="/Feedback/AdminList">Back</a><br>
    <a class="navlink" href="/Feedback/Update/@Model.Feedback.feedback_id">Update</a><br>
    <a class="navlink" href="/Feedback/DeleteConfirm/@Model.Feedback.feedback_id">Delete</a>
</div>

<div style="overflow:hidden;">
    <table>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.fname) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.fname)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.lname) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.lname)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.email) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.email)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.title) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.title)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.text) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.text)
            </td>
        </tr>
    </table>
</div>

Views/Feedback/Create.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.FeedbackDto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<div class="navbar">
    <a class="navlink" href="/Feedback/AdminList">Back</a>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Team</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.fname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.Hidden("DepartmentId", 1)

    @Html.Hidden("date", DateTime.Now)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

Views/Feedback/DeleteConfirm.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.FeedbackModel

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Delete Feedback</h2>

<div class="navbar">
    <a class="navlink" href="/Feedback/AdminShow/@Model.feedback_id">Back</a>
</div>

<h2> Are you sure you want to delete @Html.DisplayFor(model => model.title) ? </h2>

<form method="POST" action="/Feedback/Delete/@Model.feedback_id">
    <div class="inpfield"><input type="submit" value="Confirm" /></div>
</form>

Views/Feedback/List.cshtml
@model IEnumerable<Red_Lake_Hospital_Redesign_Team6.Models.FeedbackDto>

@{
    ViewBag.Title = "List";
}

<h2>Feedback List</h2>

<table class="table">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            email
        </th>
        <th>
            title
        </th>
        <th>
            text
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.text)
            </td>
            <td>
                <a href="/Feedback/Show/@item.feedback_id">Read More</a>
            </td>
        </tr>
    }

</table>

Views/Feedback/Show.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.ViewModels.ShowFeedbackViewModel

@{
    ViewBag.Title = "Show";
}

<h2>@Model.Feedback.title</h2>
<div class="navbar">
    <a class="navlink" href="/Feedback/List">Back</a>
</div>

<div style="overflow:hidden;">
    <table>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.fname) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.fname)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.lname) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.lname)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.email) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.email)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.title) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.title)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Feedback.text) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Feedback.text)
            </td>
        </tr>
    </table>
</div>

Views/Feedback/Update.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.ViewModels.UpdateFeedbackViewModel

@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>

<div class="navbar">
    <a class="navlink" href="/Feedback/AdminShow/@Model.Feedback.feedback_id">Back</a>
</div>

@using (Html.BeginForm("Update", "Feedback", new { id = Model.Feedback.feedback_id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update Player</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Feedback.feedback_id, new { Name = "blog_id" })
        <div class="row">
            <div class="col-md-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.Feedback.fname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Feedback.fname, new { htmlAttributes = new { @class = "form-control", Name = "fname" } })
                        @Html.ValidationMessageFor(model => model.Feedback.fname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Feedback.lname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Feedback.lname, new { htmlAttributes = new { @class = "form-control", Name = "lname" } })
                        @Html.ValidationMessageFor(model => model.Feedback.lname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Feedback.email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Feedback.email, new { htmlAttributes = new { @class = "form-control", Name = "email" } })
                        @Html.ValidationMessageFor(model => model.Feedback.email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Feedback.title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Feedback.title, new { htmlAttributes = new { @class = "form-control", Name = "title" } })
                        @Html.ValidationMessageFor(model => model.Feedback.title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Feedback.text, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Feedback.text, new { htmlAttributes = new { @class = "form-control", Name = "text" } })
                        @Html.ValidationMessageFor(model => model.Feedback.text, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.Hidden("DepartmentId", 1)

                @Html.Hidden("date", DateTime.Now)

                <div class="form-group">
                    <div class="submit">
                        <input type="submit" value="submit" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}