Models/Testimonial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Red_Lake_Hospital_Redesign_Team6.Models
{
    public class Testimonial
    {
        [Key]
        public int testimonial_Id { get; set; }

        [Required(ErrorMessage = "Please Enter Testimonial Content.")]
        [AllowHtml]
        public string testimonial_Content { get; set; }

        [Required(ErrorMessage = "Please Enter a First Name.")]
        public string first_Name { get; set; }

        [Required(ErrorMessage = "Please Enter a Last Name.")]
        public string last_Name { get; set; }

        [Required(ErrorMessage = "Please Enter an Email.")]
        public string email { get; set; }

        [Required(ErrorMessage = "Please Enter a Phone Number.")]
        public int phone_Number { get; set; }
        public bool Has_Pic { get; set; }
        public string Pic_Extension { get; set; }

        [Required(ErrorMessage = "Please Enter a Posted Date.")]
        public DateTime posted_Date { get; set; }
        public bool Approved { get; set; }

        [ForeignKey("ApplicationUser")]
        public string Id { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public ICollection<DepartmentsModel> Departments { get; set; }

    }
    public class TestimonialDto
    {
        public int testimonial_Id { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Please Enter Testimonial Content.")]
        public string testimonial_Content { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "Please Enter a First Name.")]
        public string first_Name { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Please Enter a Last Name.")]
        public string last_Name { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Please Enter a Email.")]
        public string email { get; set; }

        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Please Enter a Phone Number.")]
        public int phone_Number { get; set; }

        public bool Has_Pic { get; set; }
        public string Pic_Extension { get; set; }
        public DateTime posted_Date { get; set; }
        public bool Approved { get; set; }
        public string Id { get; set; }
    }
}

Controllers/TestimonialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Red_Lake_Hospital_Redesign_Team6.Models;
using Red_Lake_Hospital_Redesign_Team6.Models.ViewModels;
using System.Net.Http.Headers;
using System.Net.Http;
using System.Diagnostics;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;

namespace Red_Lake_Hospital_Redesign_Team6.Controllers
{
    public class TestimonialController : Controller
    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static TestimonialController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                UseCookies = false,
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:44349//api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Gets the authentication credentials which are sent to the controller.
        /// </summary>

        private void GetApplicationCookie()
        {
            string token = "";
            //HTTP client is set up to be reused, otherwise it will exhaust server resources.
            //This is a bit dangerous because a previously authenticated cookie could be cached for
            //a follow-up request from someone else. Reset cookies in HTTP client before grabbing a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;
            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        /// <summary>
        ///  Renders the view for creating a new Testimonial
        /// </summary>
        /// <returns>Returns a view for creating a new Testimonial</returns>
        /// <example>
        /// GET : Testimonial/Create/2
        /// </example>

        [Authorize(Roles = "admin,user")]
        [HttpGet]
        public ActionResult Create(int id)
        {
            string url = "DepartmentData/FindDepartment/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                ViewBag.Id = id;
                return View();
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Creates a new Testimonial in the database
        /// </summary>
        /// <param name="TestimonialInfo">Form data which has the details for the new Testimonial to be entered into the database</param>
        /// <returns>
        ///     If successfull , A new Testimonial would be entered into the database.
        ///     If not , then an error would be thrown 
        /// </returns>
        /// <example>
        /// POST: Testimonial/Create/1
        /// </example>

        [HttpPost]
        [Route("Testimonial/Create/{DepartmentId}")]
        [Authorize(Roles = "admin,user")]
        public ActionResult Create(int id, Testimonial TestimonialInfo, HttpPostedFileBase TestimonialPic)
        {
            GetApplicationCookie();
            TestimonialInfo.Id = User.Identity.GetUserId();
            string url = "TestimonialData/AddTestimonial/" + id;
            HttpContent content = new StringContent(jss.Serialize(TestimonialInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                int Id = response.Content.ReadAsAsync<int>().Result;
                //only attempt to send Movie picture data if we have it
                if (TestimonialPic != null)
                {
                    //Send over image data for movie
                    url = "TestimonialData/UpdateTestimonialPic/" + Id;
                    MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                    HttpContent imagecontent = new StreamContent(TestimonialPic.InputStream);
                    requestcontent.Add(imagecontent, "TestimonialPic", TestimonialPic.FileName);
                    response = client.PostAsync(url, requestcontent).Result;
                }
                return RedirectToAction("DetailsofDepartment", "Department", new { Id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Renders the view to update a testimonial
        /// </summary>
        /// <param name="TestimonialId">Id of the testimonial to be updated</param>
        /// <param name="DepartmentId">Id of the department of which the testimonial is a part of.</param>
        /// <returns>
        ///     If successfull , returns a ViewModel which contains details about the testimonial and the department 
        ///     of which the testimonial is a part of.
        ///     If not successfull , returns an error.
        /// </returns>
        /// <example>
        ///     GET: Testimonial/UpdateTestimonial/1/2
        /// </example>

        [HttpGet]
        [Authorize(Roles = "admin,user")]
        public ActionResult UpdateTestimonial(int TestimonialId, int DepartmentId)
        {
            TestimonialDetails Testimonial_Details = new TestimonialDetails();

            string url = "TestimonialData/FindTestimonial/" + TestimonialId;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                TestimonialDto testimonial = response.Content.ReadAsAsync<TestimonialDto>().Result;
                Testimonial_Details.TestimonialDto = testimonial;

                url = "DepartmentData/FindDepartment/" + DepartmentId;
                response = client.GetAsync(url).Result;
                DepartmentsDto department = response.Content.ReadAsAsync<DepartmentsDto>().Result;
                Testimonial_Details.DepartmentDto = department;

                return View(Testimonial_Details);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Updates the information of a testimonial in the database.
        /// </summary>
        /// <param name="TestimonialDetails">View Model object which contains information of the testimonial 
        /// and the department</param>
        /// <returns>
        ///     If connection to the api is successfull, updates the contents of the existing testimonial and the control is 
        ///     redirected to the Action "DetailsofDepartment" which renders the view to display the details of the department
        ///     If not successfull, then an error message is thrown. 
        /// </returns>
        /// <example>
        ///     POST: Testimonial/UpdateTestimonial/{Form Data}
        /// </example>

        [HttpPost]
        [Authorize(Roles = "admin,user")]
        public ActionResult UpdateTestimonial(TestimonialDetails TestimonialDetails, HttpPostedFileBase TestimonialPic)
        {
            GetApplicationCookie();

            string url = "TestimonialData/UpdateTestimonial/" + TestimonialDetails.DepartmentDto.DepartmentId + "/" + TestimonialDetails.TestimonialDto.testimonial_Id;
            HttpContent content = new StringContent(jss.Serialize(TestimonialDetails.TestimonialDto));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                if (TestimonialPic != null)
                {
                    //Send over image data for movie
                    url = "TestimonialData/UpdateTestimonialPic/" + TestimonialDetails.TestimonialDto.testimonial_Id;
                    MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                    HttpContent imagecontent = new StreamContent(TestimonialPic.InputStream);
                    requestcontent.Add(imagecontent, "TestimonialPic", TestimonialPic.FileName);
                    response = client.PostAsync(url, requestcontent).Result;
                }
                return RedirectToAction("DetailsofDepartment", "Department", new { Id = TestimonialDetails.DepartmentDto.DepartmentId });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// Asks the user to confirm before deleting the Testimonial from the database permanently. Shows the information about the testimonial   
        /// </summary>
        /// <param name="DepartmentId">Id of the Department to be deleted.</param>
        /// <param name="TestimonialId">Id of the Testimonial to be deleted.</param>
        /// <returns>
        ///     If successfull, renders the details of the Testimonial to be deleted to the corresponding View.
        ///     If not successfull, then returns an error.
        /// </returns>
        /// <example>
        ///     GET: Testimonial/DeleteConfirm/5/2
        /// </example>

        [HttpGet]
        [Authorize(Roles = "admin,user")]
        public ActionResult DeleteConfirm(int DepartmentId, int TestimonialId)
        {

Views/Testimonial/Create.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.Testimonial

@{
    ViewBag.Title = "Create";
}

<h2>Create Testimonial</h2>

@using (Html.BeginForm("Create", "Testimonial", new { id = ViewBag.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.testimonial_Content, "Testimonial Content :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.testimonial_Content, new { htmlAttributes = new { @class = "form-control textarea-departmentdetails admin", Name = "testimonial_Content" } })
                @Html.ValidationMessageFor(model => model.testimonial_Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.first_Name, "First Name :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_Name, new { htmlAttributes = new { @class = "form-control", Name = "first_Name" } })
                @Html.ValidationMessageFor(model => model.first_Name, "", new { @class = "text-danger", data_valmsg_for = "first_Name" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_Name, "Last Name :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, "Email :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_Number, "Phone Number :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.posted_Date, "Posted Date :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.posted_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.posted_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="">
                <label for="TestimonialPic">Picture:</label>
                <input type="file" name="TestimonialPic" id="TestimonialPic" class="choosefile" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DetailsofDepartment", "Department", new { id = ViewBag.Id }, null)
</div>

Views/Testimonial/DeleteConfirm.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.ViewModels.TestimonialDetails
@{
    ViewBag.Title = "DeleteConfirm";
}


<h3>Are you sure you want to delete this Testimonial of Department : @Model.DepartmentDto.DepartmentName?</h3>
<hr />
@using (Html.BeginForm("DeleteTestimonial", "Testimonial", FormMethod.Post))
{
    <div class="card departmentdetails-card" style="width: 18rem;">
        <div class="card-body">
            <h3 class="card-title">@Model.TestimonialDto.first_Name @Model.TestimonialDto.last_Name </h3>
            <p class="card-text">@Html.Raw(@Model.TestimonialDto.testimonial_Content)</p>
            <div class="department-button">
                <input type="hidden" name="TestimonialId" value="@Model.TestimonialDto.testimonial_Id" />
                <input type="hidden" name="DepartmentId" value="@Model.DepartmentDto.DepartmentId" />
                <input type="submit" value="Delete" class="btn btn-primary department-button" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to Department Details", "DetailsofDepartment", "Department", new { Id = Model.DepartmentDto.DepartmentId }, null)
</div>

Views/Testimonial/UpdateTestimonial.cshtml
@model Red_Lake_Hospital_Redesign_Team6.Models.ViewModels.TestimonialDetails

@{
    ViewBag.Title = "UpdateTestimonial";
}

<h1>Department : @Model.DepartmentDto.DepartmentName</h1>
<h2>Update Testimonial</h2>

@using (Html.BeginForm("UpdateTestimonial", "Testimonial", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TestimonialDto.testimonial_Id)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentDto.DepartmentId)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentDto.DepartmentId)

        @Html.HiddenFor(model => model.TestimonialDto.Id)

        @Html.HiddenFor(model => model.TestimonialDto.Approved)

        <div class="form-group">
            @Html.LabelFor(model => model.TestimonialDto.testimonial_Content, "Content :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.TestimonialDto.testimonial_Content, new { htmlAttributes = new { @class = "form-control", Name = "TestimonialDto_testimonial_Content" } })
                @Html.ValidationMessageFor(model => model.TestimonialDto.testimonial_Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestimonialDto.first_Name, "First Name :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestimonialDto.first_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestimonialDto.first_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestimonialDto.last_Name, "Last Name :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestimonialDto.last_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestimonialDto.last_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestimonialDto.email, "Email :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestimonialDto.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestimonialDto.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestimonialDto.phone_Number, "Phone Number :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestimonialDto.phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestimonialDto.phone_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestimonialDto.posted_Date, "Posted Date :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestimonialDto.posted_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestimonialDto.posted_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="TestimonialPic">Picture:</label>
                <input type="file" name="TestimonialPic" id="TestimonialPic" class="choosefile" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="hidden" value="@Model.TestimonialDto.UserId" name="UserId"/>*@
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Department Details", "DetailsofDepartment", "Department", new { Id = Model.DepartmentDto.DepartmentId }, null)
</div>